version: "3"

services:
  389ds:
    image: 4teamwork/389ds:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 10389:3389
      - 10636:3636
    volumes:
      - ./data:/data
    environment:
      - SUFFIX_NAME=dc=example,dc=com
      - DS_DM_PASSWORD=secret
